name: docker-ci

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Find Git Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: 'HEAD'
          skip-unshallow: 'true'
          abbrev: 7
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker scratch meta
        id: scratch_meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Build and push scratch image
        id: docker_build_scratch
        uses: docker/build-push-action@v5
        with:
          context: .
          target: scratch
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7
          push: true
          tags: ${{ steps.scratch_meta.outputs.tags }}
          labels: ${{ steps.scratch_meta.outputs.labels }}
          build-args: 'GIT_DESC=${{steps.tagger.outputs.tag}}'
      -
        name: Docker alpine meta
        id: alpine_meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          flavor: |
            suffix=-alpine,onlatest=true
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Build and push alpine image
        id: docker_build_alpine
        uses: docker/build-push-action@v5
        with:
          context: .
          target: alpine
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7
          push: true
          tags: ${{ steps.alpine_meta.outputs.tags }}
          labels: ${{ steps.alpine_meta.outputs.labels }}
          build-args: 'GIT_DESC=${{steps.tagger.outputs.tag}}'
